name: 'Checkout Repository'

description: 'Checkout the repository and fetch all branches'

runs:
  using: 'composite'
  steps:
    - name: Clone repository
      shell: bash
      run: |
        git clone "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" .
        git fetch --all
