// SPDX-License-Identifier: GPL-2.0
/*
 * Driver for the Analog Devices ADSD3500 chip.
 *
 * Copyright (C) 2021 Analog Devices, All Rights Reserved.
 *
 */

#ifndef _ADSD3500_REGS_H_
#define _ADSD3500_REGS_H_

#include <linux/bitfield.h>

#define REVERSE_SHORT(x) ((0x0000FF00 & x << 8) | (0x000000FF & x >> 8))
#define REVERSE_LONG(x) ( ((x&0xff000000)>>24) | (((x&0x00ff0000)<<8)>>16) | (((x&0x0000ff00)>>8)<<16) | ((x&0x000000ff) << 24) )

#define GET_CHIP_ID_CMD						0x01120000

#define STREAM_ON_CMD						0x00AD00C5

#define STREAM_OFF_CMD						0x000C0002

#define SET_IMAGER_MODE_CMD					0xDA00
#define SET_IMAGER_MODE_MSK					GENMASK(7, 0)
#define SET_IMAGER_MODE(x)				    FIELD_PREP(SET_IMAGER_MODE_MSK, x)
#define SET_IMAGER_MODE_DEPTH_EN_MSK		BIT_MASK(0)
#define SET_IMAGER_MODE_DEPTH_EN(x)		    FIELD_PREP(SET_IMAGER_MODE_DEPTH_EN_MSK, x)
#define SET_IMAGER_MODE_VC_EN_MSK			BIT_MASK(1)
#define SET_IMAGER_MODE_VC_EN(x)			FIELD_PREP(SET_IMAGER_MODE_VC_EN_MSK, x)
#define SET_IMAGER_MODE_AB_EN_MSK			BIT_MASK(2)
#define SET_IMAGER_MODE_AB_EN(x)			FIELD_PREP(SET_IMAGER_MODE_AB_EN_MSK, x)
#define SET_IMAGER_MODE_AB_AVG_EN_MSK		BIT_MASK(3)
#define SET_IMAGER_MODE_AB_AVG_EN(x)		FIELD_PREP(SET_IMAGER_MODE_AB_AVG_EN_MSK, x)
#define SET_IMAGER_MODE_DEPTH_BITS_MSK		GENMASK(6, 4)
#define SET_IMAGER_MODE_DEPTH_BITS(x)		FIELD_PREP(SET_IMAGER_MODE_DEPTH_BITS_MSK, x)
#define SET_IMAGER_MODE_AB_BITS_MSK			GENMASK(9, 7)
#define SET_IMAGER_MODE_AB_BITS(x)  		FIELD_PREP(SET_IMAGER_MODE_AB_BITS_MSK, x)
#define SET_IMAGER_MODE_CONF_BITS_MSK		GENMASK(11, 10)
#define SET_IMAGER_MODE_CONF_BITS(x)		FIELD_PREP(SET_IMAGER_MODE_CONF_BITS_MSK, x)
#define SET_IMAGER_MODE_MIPI_LANES_NR_MSK   GENMASK(13, 12)
#define SET_IMAGER_MODE_MIPI_LANES_NR(x)    FIELD_PREP(SET_IMAGER_MODE_MIPI_LANES_NR_MSK, x)

#define GET_IMAGER_MODE_CMD					0x0012
#define GET_IMAGER_AB_INVLD_TRSHLD			0x0015
#define GET_IMAGER_CONFIDENCE_TRSHLD		0x0016
#define GET_IMAGER_JBLF_STATE				0x0017
#define GET_IMAGER_JBLF_FILT_SIZE			0x0018
#define GET_IMAGER_STATUS_CMD				0x00200000

#define SET_FRAMERATE_CMD                   0x0022
#define GET_FRAMERATE_CMD                   0x00230000

#define READ_REGISTER_CMD					0xFFFF
#define WRITE_REGISTER_CMD					0xFFFF

#define SWITCH_TO_BURST_CMD         	    0x00190000

#define ADSD3500_CHIP_ID					0x5931
#define USER_TASK 				_IOW('A',1,int32_t*)
#define SIGETX 					44
#define ADSD3500_FIRMWARE			"adi/adsd3500-fw.bin"
#define HEADER_SIZE_IN_BYTES             	16
#define PAYLOAD_MAX_CHUNK_SIZE			2049
#define	ADSD3500_SPI_WRITE_CMD			0x40
#define ADSD3500_SPI_READ_CMD			0x80

#endif
